veraison/services

- proto/result.proto
Correct the spelling of the json_name "veraison-processed-evidence"
inside  AttestationResult message.
This addresses https://github.com/veraison/services/issues/6
> proto: fix typo inside result.proto

- mk/test.mk
Make sure mockgen is installed on the system before attempting to run
tests, requesting that the user install it if it isn't.
> mk: check for mockgen before test

- kvstore/common.go
- kvstore/ikvstore.go
- kvstore/memory.go
- kvstore/memory_test.go
- kvstore/sql.go
- kvstore/sql_test.go
- vts/policymanager/Makefile
- vts/policymanager/policymanager.go
- vts/policymanager/policymanager_test.go
- vts/trustedservices/trustedservices_grpc.go
- Handle key not being set inside a kvstore as a distinct case from other
failure mode buy specifying a new error type.
- Fix the handling of policy not being found inside policymanager.
- Consider no endorsements being associated with a token to be a valid situation
in the general case.
This addresses https://github.com/veraison/services/issues/25
> kvstore ErrKeyNotFound and associated fixes

- vts/policymanager/policymanager.go
Use errors.Is to detect ErrNoPolicy that may be wrapped.
This (re-)addresses https://github.com/veraison/services/issues/25
> vts: fix no policy case for policymanager

- policy/cmd/polcli/commands/root.go
Specify config.Version (which gets populated at build time by git commit/tag) as the version for the executable.
Together with  https://github.com/veraison/services/pull/50, this implements https://github.com/veraison/services/issues/51
> policy: polcli version set from git

- Makefile
- deployments/docker/Dockerfile
- deployments/docker/README.md
- deployments/docker/config-templates/provisioning_tmpl.j2
- deployments/docker/config-templates/verification_tmpl.j2
- deployments/docker/config-templates/vts_tmpl.j2
- deployments/docker/default.env
- deployments/docker/docker-compose.yml
- deployments/docker/generate-config.py
- mk/common.mk
- provisioning/Makefile
- verification/Makefile
- vts/Makefile
- vts/cmd/vts-service/config.yaml
- vts/test-harness/init-kvstores.sh
Previously, setting up the veraison services was complex as each service and their dependencies needed to be manually instantiated. This made the setting up demos time consuming. Now, veraison services can be built and deployed into containers using `docker compose`, allowing easy setup of demo environments. Configuration of the services within Docker have also been streamlined to obtain settings from a provided .env file.
This addresses #41
> docker deployment + documentation

- provisioning/decoder/decoder_rpc.go
- provisioning/plugins/common/unsignedcorim_decoder.go
A couple of small changes to make CoRIM decode errors clearer and more informative.
> Clarify CoRIM errors

- scheme/ischeme.go
Update the doc comment for ValidateEvidenceIntegrity to explain the need for it taking endorsements as an argument.
Signed-off-by: Sergei Trofimov <sergei.trofimov@arm.com>
> scheme: clarify ValidateEvidenceIntegrity usage.

- .github/workflows/integration-tests.yml
- deployments/docker/Dockerfile
- deployments/docker/config-templates/provisioning_tmpl.j2
- deployments/docker/config-templates/verification_tmpl.j2
- deployments/docker/config-templates/vts_tmpl.j2
- deployments/docker/default.env
- deployments/docker/demo.env
- deployments/docker/docker-compose.yml
- integration-tests/Makefile
- integration-tests/docker-compose-integration-tests.yml
- integration-tests/include.yaml
- integration-tests/tavern.Dockerfile
- integration-tests/test_end_to_end_success.tavern.yaml
- integration-tests/test_utils.py
- scripts/integ-fail.py
- vts/Makefile
This change implements:
- An end to end integration test using Tavern (a pytest based API testing framework)
- A new Github action workflow to integrate the integration tests into the CI pipeline
This addresses #84
> Add end to end integration test and make new integration test workflow

- .github/workflows/integration-tests.yml
- deployments/docker/default.env
- integration-tests/README.md
- integration-tests/conftest.py
- integration-tests/docker-compose-integration-tests.yml
- integration-tests/include.yaml
- integration-tests/tavern.Dockerfile
- integration-tests/test_bad_swcomp_claim.tavern.yaml
- integration-tests/test_provisioning_unsuccessful.tavern.yaml
- integration-tests/test_utils.py
- integration-tests/test_verification_bad_nonce_relying_party.tavern.yaml
- integration-tests/test_verification_bad_session_attester.tavern.yaml
This change adds documentation describing how to write end to end integration tests using the python Tavern testing framework. This change also adds some negative end to end tests that test the HTTP responses when given incorrect stimuli.
This work contributes to #84
> Add integration test documentation and negative testing

- go.mod
- go.sum
- scheme/cca-ssd-platform/evidence_handler.go
- scheme/psa-iot/evidence_handler.go
Evaluate the security life cycle in order to populate the instance identity, runtime opaque, and storage opaque trust vector claims.
> scheme/{psa,cca}: add life cycle evaluation

- README.md
Rephrase the end-to-end section of the README, to not imply that the end-to-end script is the authoritative way of doing provisioning and verification using Veraison, rather than just an example.
> README: de-authorize end-to-end section

- capability/well-known.go
- provisioning/api/handler.go
- provisioning/api/handler_test.go
- provisioning/api/router.go
- verification/api/handler.go
- verification/api/handler_test.go
- verification/api/router.go
This change adds unit tests to test the implemented discovery APIs
This addresses #80
> Add discovery API unit tests

- README.md
- deployments/docker/README.md
- kvstore/README.md
- perf/reports/report-2023-05.md
Add a warning about the default deployment not being suitable for performance testing due to the use of sqlite3.
> Add a warning RE the use of sqlite3 in deployments

- config/cmdline.go
- config/viper.go
- provisioning/cmd/provisioning-service/main.go
- verification/cmd/verification-service/main.go
- vts/cmd/vts-service/main.go
enable the following cmd line switches for all services:
```
-c, --config <configuration-file> (default "config.yaml")
-h, --help
-v, --version
```
> minimal command line treatment for services

- deployments/docker/Makefile
Makefile targets for the individual containers (e.g. "vts" depend o resolution of ".built/%-container", which, in turn, depends on the resolution of ".built/%-image". The latter has $DEPLOY_DEST as its prerequisite, and, it appears, does not resolve if that prerequisite does not yet exist.
To fix this, add "deploy" (which creates $DEPLOY_DEST" as an explicit prerequisite for container and image targets, head of  the ".built/*" prerequisites.
> deploy/docker: fix individual container make targets

- scheme/parsec-tpm/evidence_handler.go
Needs to be Base64 URL-safe w/out padding
> Parsec TPM plugin: fix encoding of the `akpub` claim

- scheme/cca-ssd-platform/evidence_handler.go
CCA FVP data uses identical Measurement Values for multiple SW components.
Hence the `matchSoftware` check fails, if ONLY using Measurement Values as index.
This PR enhances the index to include "Measurement Type".
> Enhance matching index to include Measurement Type

- .gitignore
- builtin/builtin_loader.go
- builtin/builtin_manager.go
- deployments/docker/README.md
- integration-tests/data/claims/enacttrust.badnode.json
- integration-tests/data/endorsements/comid-enacttrust-badta.json
- integration-tests/data/results/enacttrust.badnode.json
- integration-tests/tests/common.yaml
- integration-tests/tests/test_enacttrust_badkey.tavern.yaml
- integration-tests/tests/test_enacttrust_badnode.tavern.yaml
- integration-tests/utils/generators.py
- integration-tests/utils/hooks.py
- scheme/tpm-enacttrust/evidence_handler.go
- scheme/tpm-enacttrust/extractor.go
- scheme/tpm-enacttrust/test/cmd/gen-token/README.md
- scheme/tpm-enacttrust/test/cmd/gen-token/main.go
- vts/cmd/vts-service/main.go
Fixes for a number of issues identified while debugging enacttrust attestation scheme. As well as fixes to the enacttrust scheme, and some minor typo/doc updates, this incudes fixes to the builtin plugin loader (that became broken when the endorsement decoder plugins were moved from `provisioning` to `vts`).
> enacttrust fixes

- scheme/tpm-enacttrust/evidence_handler.go
Evidence processing is checking that the hash in the evidence matches the provisioned reference value, and sets status to affirming if it does.
However, prior to this, it was not doing anything otherwise. This means that in case of failed attestation, the result status remained as "none".
This commit sets status to contraindicated (and executables trust vector claim to unknown runtime) if reference value comparison fails.
> scheme/tpm-enacttrust: fix failed attestation result

- deployments/docker/src/builder-dispatcher
- deployments/docker/src/builder.docker
Create and set ownership of the build directory inside the Dockerfile
Fix #193
> set ownership of the build directory earlier

- verification/api/handler.go
- verification/api/handler_test.go
Up to this point, on session creation, nonceSize parameter was required to be a non-zero uint8 (i.e. in range 1..255), and the nonce parameter was only verified to be  a valid base64 string, with no size limit.
The nonce eventually ends up inside EAR's eat_nonce claim, and therefore must comport with the restriction associated with that claim, which is between 8 and 64 bytes long. This will result in a failed attestation result generation in the subsequent submit request.
This commit modifies nonceSize limit check to be aligned with eat_nonce definition, and adds an analogous check for the nonce parameter. This will insure that attempting to define a nonce of an invalid size during session creation will result in a failure to create the session.
> verification: nonce size validation on session create

- scheme/cca-ssd-platform/evidence_handler.go
Ensure that if the session nonce is less than 64 bytes, it gets zero-padded to that size, as this will be done to cca-realm-challenge inside the attestation token.
See https://developer.arm.com/documentation/den0137/latest, p 92
Thanks to @thomas-fossati for spotting this.
> scheme/cca-ssd-platform: zero-pad session nonce

- README.md
The current URL in the README file points to that code in a no-longer existent branch, `migration`. This now points it to `main`.
> Update link for kvstore subsystem

- end-to-end/walkthrough.md
This guide explains how to setup a verifier and an attester. To produce a workable example setup, it is necessary to 
- create attestation keys on the attester,
- provisioning trust anchors, reference values and endorsements on the verifier, and
- to create evidence on the attester for consumption by the verifier.
For this example setup evidence is provided in form of an PSA attestation token.
> Attestation Walkthough

- scheme/cca-ssd-platform/endorsement_handler_test.go
- scheme/common/Makefile
- scheme/common/arm/Makefile
- scheme/parsec-cca/endorsement_handler_test.go
- scheme/parsec-tpm/endorsement_handler_test.go
- scheme/psa-iot/endorsement_handler_test.go
- Make sure tests inside `scheme/common/arm` are run as part of `make test`
- Remove unnecessary  pre hook inside `scheme/common/Makefile` that caused problems by triggering copyright checks during Docker deployment creation.
This addresses https://github.com/veraison/services/issues/212
> Makefile fixes

- handler/evidence_rpc.go
- handler/ievidencehandler.go
- handler/istorehandler.go
- handler/store_rpc.go
- scheme/cca-ssd-platform/evidence_handler.go
- scheme/cca-ssd-platform/evidence_handler_test.go
- scheme/cca-ssd-platform/store_handler.go
- scheme/parsec-cca/evidence_handler.go
- scheme/parsec-cca/store_handler.go
- scheme/parsec-tpm/common.go
- scheme/parsec-tpm/evidence_handler.go
- scheme/parsec-tpm/evidence_handler_test.go
- scheme/parsec-tpm/store_handler.go
- scheme/psa-iot/evidence_handler.go
- scheme/psa-iot/evidence_handler_test.go
- scheme/psa-iot/store_handler.go
- scheme/riot/evidence_handler.go
- scheme/riot/evidence_handler_test.go
- scheme/riot/store_handler.go
- scheme/tpm-enacttrust/evidence_handler.go
- scheme/tpm-enacttrust/evidence_handler_test.go
- scheme/tpm-enacttrust/store_handler.go
- vts/trustedservices/trustedservices_grpc.go
Move reference value ID extraction from evidence into store handler.
Prior to this, it was done inside evidence handler as part of claims
extraction.
This ensure that ID generation on both provisioning and verification
paths is handled in the same place, and is symmetrical with trust anchor
ID generation.
This also means that ExtractClaims method is now responsible _only_ for
claim extraction. ExtractedClaims structure is removed, and the method
now returns the map[string]interface{} claims set (ExtractedClaims
combined that with reference IDs).
This addresses: https://github.com/veraison/services/issues/214
> handler: add GetRefValueIDs to IStoreHandler 

- .github/workflows/time-tag.yml
At midnight of every 1st day of the month, the repo is tagged with a "snapshot" tag.  The tag format is "v0.0.yyMM".
> Add github action to tag the repo monthly

- scheme/cca-ssd-platform/store_handler_test.go
- scheme/cca-ssd-platform/test/extracted.json
- scheme/parsec-cca/store_handler_test.go
- scheme/parsec-tpm/store_handler_test.go
- scheme/psa-iot/store_handler_test.go
- scheme/psa-iot/test/psa-token.json
- scheme/tpm-enacttrust/store_handler_test.go
When GetRefValueIDs was moved to StoreHandler, it was no longer tested as part of the existing ExtractClaims tests. Add StoreHandler tests to rectify this.
> test(scheme): add missing GetRefValueIDs tests

- provisioning/cmd/provisioning-service/main.go
- verification/cmd/verification-service/main.go
API frontends may be started before VTS. On start up, the frontend attempts to connect to the service and if the service is not ready, it is supposed to output a warning.
This was established by checking for error from
vtsClient.GetServiceState(). However, this will not always error. If a connection cannot be established this may return no error, but report the service as down.
In addition to checking for error, check that the service state is "READY", and warn if its not.
> fix: correctly report VTS down in API server logs

- builtin/schemes.gen.go
- scheme/README.md
Update schemes.gen.go to include recent schemes (parsec-cca and parsec-tpm) and StoreHandler instances.
Due to git faffing with mtime's, make cannot always detect when the file needs to be re-generated automatically.
> fix(builtin): update schemes.gen.go

- deployments/docker/src/builder.docker
dlv@v1.23.0 is incompatible with golang 1.19 which is used by the docker builder.
This change pins dlv version to @v1.22.1 in the builder's Dockerfile to avoid breaking the 'docker-deployment' target.
Fix #247
> fix(docker): pin dlv version to v1.22.1

- deployments/docker/src/builder.docker
- deployments/docker/src/keycloak.docker
- deployments/docker/src/management.docker
- deployments/docker/src/manager.docker
- deployments/docker/src/provisioning.docker
- deployments/docker/src/verification.docker
- deployments/docker/src/vts.docker
- integration-tests/docker/Dockerfile
Latest docker started reporting warnings that the "FROM" and "as" cases don't match.
> fix(docker): fix case mismatch warnings

- Makefile
Enable the building of a single, combined plugin per scheme.
Having separate plugins for different handler interfaces originally made some sense, as they were being loaded by different services (and could therefore be potentially deployed to different systems).
Since 20277644, all interfaces are loaded by the VTS, so having separate plugins for them no longer makes any sense.
Other reasons to combine plugins:
- It shortens build time quite significantly. On my system, by about eight seconds:
```
$ for i in $(seq 1 3); do
make clean &>/dev/null && \ 
{ time make &>/dev/null; } 2>&1 \ 
| grep real | cut -f2;
done 
0m19.769s
0m19.611s
0m19.635s
```
and with combined plugins:
```
0m11.876s
0m11.854s
0m11.883s
```
- It results in less space being consumed on disk. The vast majority of the size …
> chore: enable combined plugins by default

- deployments/native/deployment.sh
The deployment.sh script install a version of cocli that is not compatible with the new CoRIM template format.
This brings parity between native and docker deployments.
> fix: install the latest cocli in the native deployment too

- deployments/native/bootstrap/ubuntu.sh
The Ubuntu bootstrap script assumes x86 as the target architecture.  When running on Arm, the installation of the step CLI package breaks.
> fix(deployment): make bootstrap architecture-aware

- deployments/docker/src/builder.docker
Upgrade the pocli tool in the docker deployment to the latest version as it is in native deployment.
Fix #268
> deploy/docker: Update pocli version

- deployments/docker/Makefile
> fix(docker): remove management service image on `clean-docker`

- mk/cmd.mk
- mk/plugin.mk
cgo allows the use of C libraries in GoLang. Some packages like sqlite3 depend on this feature.
We could allow this, barring any security issues (e.g., we can't confirm the hash of a C library before linking it).
> build: enable cgo

- deployments/docker/src/manager-dispatcher
- deployments/docker/veraison
Ensure that quoting inside command line parameters is forwarded correctly to the manager container.
> fix(docker): preserve command line argument quotes

- provisioning/api/handler.go
- provisioning/provisioner/provisioner.go
> fix: error handling of malformed media types

- deployments/aws/deployment.sh
- deployments/debian/deployment.sh
- deployments/native/bootstrap/oraclelinux.sh
- deployments/native/deployment.sh
This PR fixes Linux distro discovery and adds a bootstrap script for Oracle Linux.
> Add bootstrap script for Oracle Linux

- README.md
Updated the Ubuntu setup instructions to include the installation of the docker-buildx plugin, which is necessary for building multi-platform Docker images. 
Fixes #284
> fix :docs add docker-buildx installation step to requirements

- deployments/docker/Makefile
Fully propagate deployment settings to the build environment.
Fix #295
> fix(docker): fully propagate deployment settings

- deployments/aws/README.md
Remove mention of needing a VPC with two public subnets from the prerequisites section of the REAME.md for the aws deployment.
This used to be the case, but now, the VPC (and the required subnets) will be created as part of the deployment.
> fix(aws): update requirements in the README

- deployments/aws/README.md
- deployments/aws/bin/veraison
- deployments/aws/deployment.sh
- deployments/aws/env/env.bash
- deployments/aws/env/env.zsh
- deployments/aws/templates/stack-services.yaml
- deployments/aws/templates/stack-support.yaml
- deployments/debian/deployment.sh
- deployments/native/deployment.sh
- deployments/rpm/deployment.sh
An attempt to create a parallel deployment (on an account that already has one) from a clean Arm-based enviroment identified a number issues with the AWS deployment automation that are being addressed here.
> AWS deployment fixes

- .github/workflows/time-package.yml
Add a workflow, triggered by the pushing of the monthly tag, that will create a Debian package based on the latest state of the code line.
This workflow also creates an attestation for the specified package.
This addresses https://github.com/veraison/services/issues/227
> feat(github): generate deb package off the monthly tag

- .github/workflows/time-package.yml
When one (or more) of the events have configuration, they cannot be specified as a list, and must instead be specified as a map with even names as keys.
> fix(github): fix "on" spec for time-package

- .github/workflows/time-package.yml
Caching started being enabled by default in v4. With it enabled, we get "Restore cache failed" warnings.
To avoid this and return to pre-v4 behavior, explicitly disable cache.
> fix(github): turn off cache for actions/setup-go@v4

- deployments/aws/README.md
- deployments/aws/deployment.cfg
- deployments/aws/deployment.sh
Make it more straight-forward to using an existing Debian package when creating the AWS deployment.
If VERAISON_DEB environment variable is specified, use the deb file it points to (using the previously-added "veraison add-deb") during "make deploy" instead of calling "veraison created-deb".
> feat(aws): option to use existing deb during make deploy

- deployments/aws/deployment.sh
Commit 87e4f625 changed to using /etc/os-release for getting the distribution ID. The ID in that is lower case, so the subsequent case statement needs to be updated.
> fix(aws): fix Ubuntu ID case in bootstrap

- deployments/aws/bin/veraison
- deployments/aws/deployment.sh
- deployments/aws/templates/stack-services.yaml
Replace the hard-coded permission boundary ARN with the parameter that was supposed to be used.
> fix(aws): replace hard-coded permission boundary

- Makefile
- deployments/rpm/deployment.sh
- deployments/rpm/veraison.spec.template
Add some fixes for the RPM deployment:
- Adds top-level Makefile target for RPM
- Updates the post install script to generate certificates with server's hostname
- Configure build version
- Add dependency on sqlite3 package
> Fixes for the RPM deployment

- integration-tests/data/results/cca.freshness-fail.json
- integration-tests/data/results/psa.badcrypto.json
- integration-tests/data/results/psa.freshness-fail.json
- vts/trustedservices/trustedservices_grpc.go
The server currently reports "integrity validation failed" when evidence integrity check fails, but it could provide a more detailed description of the problem.
> fix(vts): add details to ValidateEvidenceIntegrity failure
