veraison/services

go.mod
go.sum

Fix reported security vulnerability in OPA Module

---

end-to-end/README.md

fix typo in end2end README

---

deployments/docker/Dockerfile
provisioning/Makefile
verification/Makefile

This change automates the generation of input files for carrying out the psa demo using the docker deployment.

Automate setup of psa demo input files

---

deployments/docker/Dockerfile
deployments/docker/default.env
deployments/docker/docker-compose.yml

This change allows the Dockerfile to clone from the demo tag on the main branch in services

Change Dockerfile to clone from services at demo tag

---

deployments/docker/demo.env

Add demo.env file for ease of demo environment configuration

Add demo.env file

---

README.md

Give a brief overview of veraison command functionality in the README.md.

README: add description of veraison command

---

end-to-end/README.md

end-to-end docs cleanup

---

scheme/cca-ssd-platform/evidence_handler.go
scheme/cca-ssd-platform/evidence_handler_test.go
scheme/common/utils.go
scheme/parsec-tpm/evidence_handler.go
scheme/parsec-tpm/evidence_handler_test.go
scheme/psa-iot/evidence_handler.go
scheme/psa-iot/evidence_handler_test.go
scheme/psa-iot/test/ta-bad-key-header.json
scheme/psa-iot/test/ta-bad-key-private-key.json
scheme/psa-iot/test/ta-bad-key.json

Add the common utility function for key extraction

---

scripts/licenses.sh

Since we simplified the modules structure since we last run the scan...

update license scan tooling

---

deployments/docker/src/builder.docker
end-to-end/end-to-end
integration-tests/utils/generators.py

Align EVCLI with V2 version

---

vtsclient/vtsclient_grpc.go

make sure GetEARSigningPublicKey has a gRPC connection

---

deployments/docker/src/builder-dispatcher

Tell git our build directory is "safe"

---

go.mod
go.sum
integration-tests/data/claims/cca.good.json
integration-tests/data/policies/cca-verify-challenge.rego
integration-tests/data/results/cca.verify-challenge.json
integration-tests/tests/common.yaml
integration-tests/tests/test_cca_verify_challenge.tavern.yaml
integration-tests/utils/hooks.py
policy/agent.go
policy/agent_test.go
policy/iagent.go
policy/ibackend.go
policy/mocks/mock_ibackend.go
policy/opa.go
policy/opa.rego
policy/opa_test.go
scheme/cca-ssd-platform/evidence_handler.go
scheme/cca-ssd-platform/evidence_handler_test.go
scheme/cca-ssd-platform/test/extracted.json
vts/policymanager/mocks/iagent.go
vts/policymanager/mocks/ibackend.go
vts/policymanager/policymanager.go
vts/policymanager/policymanager_test.go
vts/trustedservices/trustedservices_grpc.go

Changes to allow policies access to the verification session nonce + fixes to nonce handling.

Nonce exposed to policy + fixes

---

integration-tests/data/results/cca.freshness-fail.json
integration-tests/data/results/psa.freshness-fail.json
integration-tests/tests/common.yaml
integration-tests/tests/test_cca_verify_challenge.tavern.yaml
integration-tests/tests/test_enacttrust_badnode.tavern.yaml
integration-tests/tests/test_freshness_check_fail.tavern.yaml
integration-tests/tests/test_multinonce.tavern.yaml
integration-tests/utils/generators.py
integration-tests/utils/hooks.py
policy/mocks/mock_ibackend.go
scheme/cca-ssd-platform/evidence_handler.go
scheme/cca-ssd-platform/evidence_handler_test.go
scheme/psa-iot/evidence_handler.go
scheme/psa-iot/evidence_handler_test.go
vts/trustedservices/trustedservices_grpc.go

Update PSA_IOT and CCA_SSD_PLATFORM schemes to perform a freshness check as part of token integrity validation.
Freshness check is integral to attestation validation to prevent replay attacks. Thus far, we have not performed it as part of our verification pipeline, and instead left it the RP. However, PSA and CCA both mandate freshness claims, and so there is no reason why this check cannot be performed as part of the scheme evidence handling, therefore reducing the risk of the RP neglecting to consider freshness and taking an affirming attestation result from Veraison at face value.

scheme: freshness check for PSA_IOT and CCA_SSD_PLATFORM

---

integration-tests/data/endorsements/comid-cca-platform-refval.json
integration-tests/data/endorsements/comid-cca-platform-ta.json
integration-tests/data/endorsements/comid-cca-realm-refval.json
integration-tests/data/endorsements/corim-cca-platform-full.json
integration-tests/data/endorsements/corim-cca-realm-full.json
integration-tests/data/results/cca.end-to-end.json
integration-tests/tests/test_cca_end_to_end.tavern.yaml
integration-tests/utils/generators.py
integration-tests/utils/hooks.py

Introduce New CCA End to End Test

Introduce Arm CCA End to End Integration Test

---

deployments/native/bin/veraison

Update show_stores() function to use the new column name.

fix(native): fix veraison show-stores command

---

deployments/docker/src/builder.docker
deployments/native/deployment.sh

fix: install latest evcli

---

deployments/native/deployment.sh

fix: install the latest cocli in the native deployment too

---

deployments/docker/src/builder.docker

fix: pin gopls version to 0.16.2

---

deployments/rpm/Makefile
deployments/rpm/README.md
deployments/rpm/deployment.cfg
deployments/rpm/deployment.sh
deployments/rpm/veraison.spec.template

Add script to build RPMs for Fedora-like distros

feat(rpm): add RPM build scripts

---

deployments/docker/veraison

fix: veraison help in docker deployment

---

auth/README.md
deployments/aws/README.md
deployments/debian/README.md
deployments/rpm/README.md
kvstore/README.md
log/README.md
management/cmd/management-service/README.md
policy/README.md
provisioning/README.md
provisioning/cmd/provisioning-service/README.md
scheme/README.md
scheme/arm-cca/README.md
scheme/psa-iot/README.md
scheme/tpm-enacttrust/README.md
verification/cmd/verification-service/README.md
vts/cmd/vts-service/README.md
vts/earsigner/README.md
vts/trustedservices/README.md

Some minor fixes and structure changes to README files across the repo to allow them to be included in Veraison book.

doc: minor changes for Veraison book
